### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by uedaeita** [amannn/next-query-params#35]
**Describe the bug**

Seems like related to https://github.com/amannn/next-query-params/issues/29, `SyntaxError: Cannot use import statement outside a module` occurs.

**To Reproduce**

1. `_app.tsx` has something like below:

```tsx
import NextAdapterApp from 'next-query-params/app'
import { QueryParamProvider } from 'use-query-params'

export default function App(props) {
  ...
  return (
    <QueryParamProvider
      adapter={NextAdapterApp}
    >
      ...
    </QueryParamProvider>
  )
}
```

2. When executing `next build`, it produces the error below:

```js
unhandledRejection /var/www/node_modules/next-query-params/dist/src/NextAdapterApp.js:2
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:[117](https://github.com/bellowl/cuisinereport/actions/runs/5522899714/jobs/10073117920#step:6:118)6:20)
    at Module._compile (node:internal/modules/cjs/loader:[121](https://github.com/bellowl/cuisinereport/actions/runs/5522899714/jobs/10073117920#step:6:122)8:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at 2470 (/var/www/.next/server/pages/_app.js:3696:18)
    at __webpack_require__ (/var/www/.next/server/webpack-runtime.js:25:42) {
  type: 'SyntaxError'
}
```

**Comment by amannn** [comment]
Thanks for the report @uedaeita! I've added https://github.com/amannn/next-query-params/pull/36 to address this. Would you mind trying out the prerelease to validate that this fixes your issue?

**Comment by uedaeita** [comment]
@amannn 
Thank you for the work! Looks like build works on my end.

**Comment by amannn** [comment]
Great to hear, thanks for checking!
